// <auto-generated />
namespace LibraryManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.0")]
    public sealed partial class latest21032025 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(latest21032025));
        
        string IMigrationMetadata.Id
        {
            get { return "202503211003434_latest21032025"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
