// <auto-generated />
namespace LibraryManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.0")]
    public sealed partial class ReaddingBorrowDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReaddingBorrowDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202503311323436_ReaddingBorrowDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
